"""The board's D6 symmetry: transforms, axis permutations, orbit relations.

This module implements §11 and the representation law of §12.1. The twelve
symmetries themselves are a property of the board rather than of any one
architecture, so they are defined in :mod:`mantisnet.d6` and re-exported here;
everything built on top of them — axis permutations, orbit classes, relation
ids — is this representation's own and lives here.

Index conventions this module fixes (each is part of the representation):

- Axis: ``AXES[a]`` is the unit step of axis ``a``, canonical order Q, R, QR.
  Axes are undirected, so a transform that negates a unit step still carries
  that axis to itself; the negation is reported separately as a reversal.
- Transform: ``D6_TRANSFORMS[t]`` maps ``(q, r)`` to its image, index ``0``
  the identity. The group is generated by the 60-degree rotation
  ``(q, r) -> (-r, q + r)`` and the reflection ``(q, r) -> (r, q)``, under
  which the engine's legality, win, and distance rules are invariant.
- Axis permutation: ``axis_permutation(t)[a]`` is the axis that axis ``a`` is
  carried to, and ``axis_reverses(t)[a]`` whether that image points the other
  way — equivalently, whether a window on axis ``a`` has its six slots
  reversed by the transform.
- Orbit id: the rank of a displacement's D6 orbit in ascending
  ``(distance, canonical dq, canonical dr)`` order. Distance leads the sort,
  so a smaller ``d_max``'s ids are a prefix of a larger one's and the radius-6
  ablation of §29 agrees with the radius-12 default on every id they share.
- Relation id: an orbit id ``0..47`` out to radius 12, then the four reserved
  ids of §11.2. The coarse ablation's ids are a separate space of its own.

Nothing here is hand-tabulated. The orbit table is generated by applying the
twelve transforms, and the axis permutations by applying them to the three
unit steps, so both remain checks on the transform table rather than a second
statement of it.
"""

from __future__ import annotations

import functools
from dataclasses import dataclass
from typing import Callable

import numpy as np

from ...d6 import D6_TRANSFORMS as _BOARD_D6

# Unit steps of the engine's axes, in canonical order Q, R, QR.
AXES = np.array([[1, 0], [0, 1], [1, -1]], dtype=np.int64)
AXES.setflags(write=False)

# §11.2. The orbit ids of the radius-12 table fill 0..47 and these sit above
# them; a table built at a smaller radius leaves its unused ids empty rather
# than shifting these down, so one relation-embedding shape serves every
# radius.
RELATION_FAR, RELATION_SELF, RELATION_LATENT, RELATION_PAD = 48, 49, 50, 51

# The reserved band starts immediately above the radius-12 orbits, so a wider
# table would collide with it.
_MAX_D_MAX = 12


# The six rotations first, index 0 the identity, then the same six after the
# reflection.
D6_TRANSFORMS = _BOARD_D6

# Column ``j`` of ``_D6_MATRICES[t]`` is where transform ``t`` sends unit
# vector ``j``. Both generators are linear, so every composition is, and the
# matrix is the whole map — which is what lets a transform be applied to a
# whole displacement array at once.
_D6_MATRICES = np.array(
    [[t((1, 0)), t((0, 1))] for t in D6_TRANSFORMS], dtype=np.int64
).transpose(0, 2, 1)
_D6_MATRICES.setflags(write=False)


def _checked_transform(t_index: int) -> int:
    """Validate a transform index against the group's size."""
    if not 0 <= int(t_index) < len(D6_TRANSFORMS):
        raise ValueError(
            f"transform index must be 0..{len(D6_TRANSFORMS) - 1}, got {t_index!r}"
        )
    return int(t_index)


def transform_coords(t_index: int, qr: np.ndarray) -> np.ndarray:
    """Apply transform ``t_index`` to an ``(..., 2)`` array of ``(q, r)``."""
    matrix = _D6_MATRICES[_checked_transform(t_index)]
    qr = np.asarray(qr, dtype=np.int64)
    if qr.ndim == 0 or qr.shape[-1] != 2:
        raise ValueError(f"coordinates must be (..., 2), got shape {qr.shape}")
    return qr @ matrix.T


def _axis_maps() -> tuple[tuple[tuple[int, int, int], ...], tuple[tuple[bool, bool, bool], ...]]:
    """Per transform, the induced axis permutation and the direction flips.

    A board symmetry carries the undirected axis set to itself, so each unit
    step's image is one unit step or its negation. Anything else means the
    transform table and ``AXES`` disagree, which would silently misroute every
    axis channel, so it is refused when the tables are built (§30.9) rather
    than left for a test to notice.
    """
    permutations, reverses = [], []
    for t in range(len(D6_TRANSFORMS)):
        images = transform_coords(t, AXES)
        permutation, flips = [], []
        for a, image in enumerate(images):
            forward = np.flatnonzero((AXES == image).all(axis=1))
            backward = np.flatnonzero((AXES == -image).all(axis=1))
            if forward.size:
                permutation.append(int(forward[0]))
                flips.append(False)
            elif backward.size:
                permutation.append(int(backward[0]))
                flips.append(True)
            else:
                raise ValueError(
                    f"transform {t} carries axis {a} to {tuple(int(c) for c in image)},"
                    " which is no axis's unit step"
                )
        if sorted(permutation) != [0, 1, 2]:
            raise ValueError(
                f"transform {t} sends the axes to {tuple(permutation)}, not a permutation"
            )
        permutations.append(tuple(permutation))
        reverses.append(tuple(flips))
    return tuple(permutations), tuple(reverses)


_AXIS_PERMUTATIONS, _AXIS_REVERSES = _axis_maps()


def axis_permutation(t_index: int) -> tuple[int, int, int]:
    """``pi[a]``: the axis that transform ``t_index`` carries axis ``a`` to."""
    return _AXIS_PERMUTATIONS[_checked_transform(t_index)]


def axis_reverses(t_index: int) -> tuple[bool, bool, bool]:
    """Whether transform ``t_index`` flips the stored direction of each axis.

    Indexed by the source axis: entry ``a`` says the unit step of axis ``a``
    maps to the negation of the unit step of ``axis_permutation(t)[a]``, so a
    window on axis ``a`` is carried to one whose slot order runs backwards.
    """
    return _AXIS_REVERSES[_checked_transform(t_index)]


def hex_distance(dq, dr):
    """Hex distance of a displacement: ``max(|dq|, |dr|, |dq + dr|)``.

    The third axis is ``(1, -1)``, so the cube coordinate the axial pair omits
    is ``-(dq + dr)`` and the cube metric ``(|x| + |y| + |z|) / 2`` collapses
    to this maximum. Vectorised over any broadcastable shapes.
    """
    dq = np.asarray(dq, dtype=np.int64)
    dr = np.asarray(dr, dtype=np.int64)
    return np.maximum(np.maximum(np.abs(dq), np.abs(dr)), np.abs(dq + dr))


def on_axis(dq, dr) -> np.ndarray:
    """The axis a displacement lies on, or ``-1`` when it lies on none (§11.3).

    The zero displacement lies on all three and is reported as ``-1``: it
    carries no direction, and the sparse paths give it ``RELATION_SELF``
    instead of a route.
    """
    dq = np.asarray(dq, dtype=np.int64)
    dr = np.asarray(dr, dtype=np.int64)
    axis = np.where(dr == 0, 0, np.where(dq == 0, 1, np.where(dq + dr == 0, 2, -1)))
    return np.where((dq == 0) & (dr == 0), -1, axis).astype(np.int64, copy=False)


@dataclass(frozen=True)
class OrbitTable:
    """The D6 displacement orbits out to ``d_max``, with their lookup grid.

    The arrays are read-only because :func:`orbit_table` hands the same
    instance to every caller.
    """

    d_max: int
    count: int
    canonical: np.ndarray  # (count, 2) the orbit's lexicographic minimum
    distance: np.ndarray  # (count,) hex distance, nondecreasing in orbit id
    grid: np.ndarray  # (2 d_max + 1,) squared, orbit id at [dq + d_max, dr + d_max]

    def lookup(self, dq, dr) -> np.ndarray:
        """Orbit ids of displacements with ``1 <= distance <= d_max``.

        Vectorised. A displacement outside that shell is an edge the builder
        should not have emitted, so it raises rather than folding into a
        catch-all class that would alias real geometry.
        """
        dq, dr = np.broadcast_arrays(
            np.asarray(dq, dtype=np.int64), np.asarray(dr, dtype=np.int64)
        )
        distance = hex_distance(dq, dr)
        outside = (distance < 1) | (distance > self.d_max)
        if outside.any():
            first = tuple(np.argwhere(outside)[0])
            raise ValueError(
                f"displacement ({int(dq[first])}, {int(dr[first])}) has hex distance"
                f" {int(distance[first])}, outside the 1..{self.d_max} orbit table"
            )
        return self.grid[dq + self.d_max, dr + self.d_max]


@functools.lru_cache(maxsize=None)
def orbit_table(d_max: int = 12) -> OrbitTable:
    """Generate the D6 displacement orbits out to ``d_max`` (§11.1).

    Every nonzero displacement in the shell is canonicalised to the
    lexicographic minimum of its twelve images; the distinct canonicals are
    ranked by ``(distance, dq, dr)``; the rank is the orbit id. Distances are
    preserved by the group, so the representative's distance is the orbit's.
    """
    if d_max < 1:
        raise ValueError(f"d_max must be at least 1, got {d_max}")
    if d_max > _MAX_D_MAX:
        raise ValueError(
            f"d_max must be at most {_MAX_D_MAX}, got {d_max}: §11.2 gives the"
            f" radius-{_MAX_D_MAX} orbits the whole id range below"
            f" RELATION_FAR = {RELATION_FAR}"
        )

    span = np.arange(-d_max, d_max + 1, dtype=np.int64)
    mesh_q, mesh_r = np.meshgrid(span, span, indexing="ij")
    displacement = np.stack([mesh_q.ravel(), mesh_r.ravel()], axis=1)
    distance = hex_distance(displacement[:, 0], displacement[:, 1])
    inside = (distance >= 1) & (distance <= d_max)
    displacement, distance = displacement[inside], distance[inside]

    # Images stay inside the shell because the group preserves distance, so a
    # stride of one shell width makes this packed key order the images exactly
    # as lexicographic ``(dq, dr)`` order does.
    images = np.stack([transform_coords(t, displacement) for t in range(len(D6_TRANSFORMS))])
    stride = 2 * d_max + 1
    keys = images[:, :, 0] * stride + images[:, :, 1]
    canonical = images[keys.argmin(axis=0), np.arange(len(displacement))]

    unique_key, first, member_orbit = np.unique(
        keys.min(axis=0), return_index=True, return_inverse=True
    )
    representative, representative_distance = canonical[first], distance[first]
    order = np.lexsort(
        (representative[:, 1], representative[:, 0], representative_distance)
    )
    rank = np.empty(len(unique_key), dtype=np.int64)
    rank[order] = np.arange(len(unique_key), dtype=np.int64)

    grid = np.full((stride, stride), -1, dtype=np.int64)
    grid[displacement[:, 0] + d_max, displacement[:, 1] + d_max] = rank[member_orbit]

    table = OrbitTable(
        d_max=d_max,
        count=len(unique_key),
        canonical=representative[order],
        distance=representative_distance[order],
        grid=grid,
    )
    for array in (table.canonical, table.distance, table.grid):
        array.setflags(write=False)
    return table


D6_ORBITS_DMAX12 = orbit_table(_MAX_D_MAX).count

# Burnside over the 468 cells at distance 1..12 confirms the count from the
# group's structure rather than from this table: the identity fixes all 468,
# the five nontrivial rotations fix none, the three axis reflections fix the
# 24 cells of a line, and the three diagonal reflections fix the 12 cells
# lying every second step along theirs — (468 + 72 + 36) / 12 = 48. A
# disagreement means a transform or the metric is wrong, never the constant.
assert D6_ORBITS_DMAX12 == 48, f"radius-12 orbits: {D6_ORBITS_DMAX12}, expected 48"


# --------------------------------------------------------------------------
# The coarse_distance_axis ablation (§29 `full_coarse_geometry`)


def coarse_relation_count(d_max: int = 12) -> int:
    """Class count of the coarse scheme: on-axis and off-axis per bucket."""
    if d_max < 1:
        raise ValueError(f"d_max must be at least 1, got {d_max}")
    return 2 * d_max


def coarse_relation(dq, dr, d_max: int = 12) -> np.ndarray:
    """The pre-orbit relation scheme: distance bucket plus on/off-axis.

    The bucket is ``min(d, d_max) - 1``, clamping at the last bucket the way
    the distance buckets of the older representation do, and it doubles for
    whether the displacement lies on an axis. *Which* axis is not part of the
    class: that is the §11.3 route, and folding it in would make the class
    depend on absolute axis identity and stop being D6-invariant. A caller
    needing SELF or PAD ids places them above :func:`coarse_relation_count`;
    the reserved ids of §11.2 belong to the orbit id space, not this one.
    """
    if d_max < 1:
        raise ValueError(f"d_max must be at least 1, got {d_max}")
    dq = np.asarray(dq, dtype=np.int64)
    dr = np.asarray(dr, dtype=np.int64)
    distance = hex_distance(dq, dr)
    if (distance < 1).any():
        raise ValueError("displacement (0, 0) has no coarse relation class")
    bucket = np.minimum(distance, d_max) - 1
    return (2 * bucket + (on_axis(dq, dr) < 0)).astype(np.int64, copy=False)
